#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# (c) Antonio Sánchez León <introlinux[fix@]gmail[fix.]com>
# (c) Miguel Anxo Bouzada <mbouzada[fix@]gmail[fix.]com>
# (c) GALPon MinNo Team <minino[fix@]galpon[fix.]org>
# july 2012

## -

case $LANG in

    es*)
	COMENZAR="Comenzar"
	PARAR="Parar"
	TRABAJANDO="trabajando"
	DESCANSANDO="descansando"
    ;;
    gl*)
	COMENZAR="Comezar"
	PARAR="Parar"
	TRABAJANDO="traballando"
	DESCANSANDO="descansando"

    ;;
    ca*)
	COMENZAR="Comenzar"
	PARAR="Parar"
	TRABAJANDO="trabajando"
	DESCANSANDO="descansando"

    ;;
    *)
	COMENZAR="Start"
	PARAR="Stop"
	TRABAJANDO="working"
	DESCANSANDO="resting"

    ;;
esac

MIN_DE_TRABAJO=25
MIN_DE_DESCANSO=5
TEMP_FILE="$HOME/.config/pomodoro"
#rm $TEMP_FILE 2>&1


if [ -f $HOME/.config/pomodoro ];then
    echo "Hay archivo de menú"
    mygtkmenu $TEMP_FILE
else
    echo "NO HAY ARCHIVO DE MENÚ"

cat > $TEMP_FILE << EOF
item = $MIN_DE_TRABAJO min $TRABAJANDO
cmd = pomodoro trabajo
icon =
item = $MIN_DE_DESCANSO min $DESCANSANDO
cmd = pomodoro descanso
icon =
SEPARATOR
item = $COMENZAR
cmd = pomodoro comenzar
icon = /usr/local/share/pixmaps/play.png
item = $PARAR
cmd = pomodoro parar
icon = /usr/local/share/pixmaps/stop.png
iconsize = 16
EOF

mygtkmenu $TEMP_FILE

fi


#while true
#do 
#    echo "Hi"
#    sleep 1
#done
